#!/usr/bin/env bash
# Ghostty terminal backend
# Config format: key = value
#
# Writes two files per apply:
#   current.conf - terminal font (font-family, font-size)
#   current.css  - tab label font (font-family, font-size for tabbar labels)
#
# The CSS file is referenced from main ghostty config via:
#   gtk-custom-css = fonts/current.css
# It merges with themes/current.css (colors from theme tool) via ghostty's
# repeatable gtk-custom-css handling.

GHOSTTY_CONFIG_DIR="$HOME/.config/ghostty/fonts"
GHOSTTY_CONFIG_FILE="$GHOSTTY_CONFIG_DIR/current.conf"
GHOSTTY_CSS_FILE="$GHOSTTY_CONFIG_DIR/current.css"

ghostty_config_path() {
  echo "$GHOSTTY_CONFIG_FILE"
}

ghostty_get_font() {
  if [[ -f "$GHOSTTY_CONFIG_FILE" ]]; then
    grep "^font-family" "$GHOSTTY_CONFIG_FILE" 2>/dev/null | cut -d= -f2 | tr -d '"' | xargs
  else
    echo ""
  fi
}

ghostty_get_size() {
  if [[ -f "$GHOSTTY_CONFIG_FILE" ]]; then
    grep "^font-size" "$GHOSTTY_CONFIG_FILE" 2>/dev/null | cut -d= -f2 | xargs
  else
    echo ""
  fi
}

# Write tab label font CSS. Rules target libadwaita AdwTabBar selectors
# (tabbar > tabbox > tab > label). Merges with theme CSS via ghostty's
# multiple gtk-custom-css file loading.
ghostty_write_css() {
  local font="$1"
  local size="$2"

  cat > "$GHOSTTY_CSS_FILE" << EOF
/* Ghostty tab font — generated by font tool.
 * Merges with themes/current.css (colors from theme tool) via gtk-custom-css.
 */
tabbar tabbox tab label,
tabbar tabbox tab .title {
  font-family: "${font}";
  font-size: ${size}pt;
}
EOF
}

ghostty_set_font() {
  local font="$1"
  local size
  size=$(ghostty_get_size)
  [[ -z "$size" ]] && size=17

  mkdir -p "$GHOSTTY_CONFIG_DIR"

  cat > "$GHOSTTY_CONFIG_FILE" << EOF
font-family = "${font}"
font-size = ${size}
EOF

  ghostty_write_css "$font" "$size"
}

ghostty_set_size() {
  local size="$1"
  local font
  font=$(ghostty_get_font)
  [[ -z "$font" ]] && font="monospace"

  mkdir -p "$GHOSTTY_CONFIG_DIR"

  cat > "$GHOSTTY_CONFIG_FILE" << EOF
font-family = "${font}"
font-size = ${size}
EOF

  ghostty_write_css "$font" "$size"
}

ghostty_apply() {
  local font="$1"
  ghostty_set_font "$font"
}
